name: Build and deploy to GitHub Pages

on:
  push:
    # Run when main or the deploy branch is updated so CI deploys the artifact
    branches: [ main, 'deploy/pages-eromosele-edeko2' ]
  # Allow manual reruns from the Actions UI
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install, build and upload
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack and prepare pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify frontmatter image references
        run: pnpm run verify:images

      - name: Build site
        run: pnpm run build

      - name: Show dist contents (diagnostic)
        run: |
          echo "Listing dist directory"
          ls -la ./dist || true
          echo "Size of dist"
          du -sh ./dist || true

      - name: Check for existing docs/ folder (possible Pages conflict)
        run: |
          if [ -d docs ]; then
            echo "WARNING: repo contains a 'docs/' directory. GitHub Pages may be serving that instead of this workflow's artifact."
            echo "Listing docs/ contents:"
            ls -la docs || true
            echo "A quick check for hard-coded base paths inside docs/ (show first matches):"
            grep -m 10 -R "href=\"/eromosele.edeko\"\|/eromosele.edeko/\|/eromosele.edeko2/\|src=\"/" docs || true
          else
            echo "No docs/ directory detected."
          fi

      - name: Upload build (dist) for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
